edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Module"
overflow_delimited_expr = true
group_imports = "StdExternalCrate"
trailing_semicolon = false
use_field_init_shorthand = true
wrap_comments = true
tab_spaces = 2
reorder_imports = true
comment_width = 80
fn_single_line = true