name: Publish

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install 1.55.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.55.0
          override: true
          components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: katyo/publish-crates@v1
      with:
        registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}